<?php
/*
 * Copyright (C) PowerOn Sistemas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this PowerOn\View\View */
?>
<!DOCTYPE html>
<html>
    <head>
        <title>PowerOn Sistemas - Error</title>
        <?php $this->html->css('poweron.css') ?>
        <?= $this->html->css() ?>
    </head>
    <body>
        <div id="header">
            <?= $this->html->img('logo.png', ['height' => 40]) ?>
        </div>
        <div id="content">
            <?= $this->content() ?>
        </div>
        <footer id="footer">
            <div id="load_time">
                T: <?= number_format(microtime(TRUE) - PO_START_TIME, 2); ?>ms
            </div>
        </footer>
    </body>
</html>